### 토큰 발급
POST http://localhost:40140/api/v1/sopo-user/token
Content-Type: application/json

{
  "username": "test@sooopo.com",
  "password": "qweqweqwe",
  "deviceId": "test124"
}

> {% client.global.set("auth_token", response.body.access_token); %}

### 진행중인 택배 가져오기
GET http://localhost:6443/api/v1/sopo-parcel/delivery/parcels/ongoing
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### 사용자의 조회 가능한 '년/월' 리스트
GET http://localhost:6443/api/v1/sopo-parcel/delivery/parcels/months
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### 택배 등록
POST http://localhost:6443/api/v1/sopo-parcel/delivery/parcel
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "carrier": "CJ_LOGISTICS",
  "waybillNum": "648346324206",
  "alias": "큐엘 무타공 멀티탭 선정리 선반 거치대"
}

### 단일 택배 조회
GET http://localhost:6443/api/v1/sopo-parcel/delivery/parcel/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}
