package team.sopo.common.enums

import org.apache.http.HttpStatus
import javax.servlet.http.HttpServletResponse

enum class ResponseEnum(val CODE: String, val MSG: String, val HTTP_STATUS: Int) {
    SUCCESS("0000", "SUCCESS", HttpStatus.SC_OK),
    ALREADY_LOGGED_IN("0010", "ALREADY_LOGGED_IN", HttpStatus.SC_CONFLICT),
    ALREADY_REGISTERED_USER("0011", "ALREADY_REGISTERED", HttpStatus.SC_BAD_REQUEST),
    VALIDATION_ERROR("VA01","", HttpStatus.SC_BAD_REQUEST),
    KAKAO_SIMPLE_FAIL("KA00", "Fail to join by kakao", HttpStatus.SC_BAD_REQUEST),
    KAKAO_SIMPLE_ALREADY_USE_EMAIL("KA01", "Already use that email", HttpStatus.SC_BAD_REQUEST),
    KAKAO_SIMPLE_NOT_VERIFYED_USER("KA02", "Can not verify kakao user", HttpStatus.SC_BAD_REQUEST),
    KAKAO_SIMPLE_CORRUPT_EMAIL("KA03", "kakao account`s email is not matched with given email", HttpStatus.SC_BAD_REQUEST),
    KAKAO_SIMPLE_FAIL_TO_PASING_DATA("KA04", "Fail to parse the kakao data", HttpStatus.SC_BAD_REQUEST),
    KAKAO_SIMPLE_CORRUPT_EMAIL2("KA05", "After verify kakao user, doesn`t match email(parameter != user data)", HttpStatus.SC_BAD_REQUEST),
    KAKAO_SIMPLE_CANNOT_FIND_FIREBASE_USER("KA06", "Can not find firebase user searched by email", HttpStatus.SC_BAD_REQUEST),
    KAKAO_SIMPLE_FAIL_TO_UPDATE_AUTH_TOKEN("KA07", "Fail to update custom token", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_FIND_API_ACCOUNT("AP01","Can`t find api account!", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_FIND_SOPO_USER("AP02", "Can`t find Sopo User", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_SAVE_API_ACCOUNT("AP03", "Fail to save Api account", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_SAVE_SOPO_USER("AP04", "Fail to save Sopo User", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_JOIN_SOPO_USER("AP05", "Fail to join..", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_CREATE_PASSWORD_RESET_TOKEN("AP06", "Fail to create jwt token", HttpStatus.SC_BAD_REQUEST),
    INVALID_USER("AP07", "Invalid user", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_GET_USER_BY_FIREBASE_UID("AP08", "Fail to get user by firebase`s uid", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_UPDATE_USER_DEVICE_INFO("AP09", "Fail to update user`s device-info", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_REQUEST_FOR_UPDATING("UP01", "Fail to request for updating", HttpStatus.SC_BAD_REQUEST),
    PARCEL_ERROR("PC00", "fail to parcel process", HttpStatus.SC_BAD_REQUEST),
    SEARCH_PARCEL_NULL_ERROR("PC01", "DeliveryTracking api`s result is null", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_SAVE_PARCEL("PC02","fail to save client`s parcel", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_SEARCH_PARCEL("PC03","fail to get client`s parcel [Delivery Api]", HttpStatus.SC_BAD_REQUEST),
    CAN_NOT_FIND_PARCEL("PC04","Can`t find a parcel", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_FIND_PARCEL("PC05","Fail to find a parcel", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_DELETE_PARCEL("PC06","Fail to delete parcels", HttpStatus.SC_BAD_REQUEST),
    ALREADY_REGISTERED_PARCEL("PC07", "Already registered parcel", HttpStatus.SC_BAD_REQUEST),
    OVER_REGISTERED_PARCEL("PC08", "The number of registration has exceeded.", HttpStatus.SC_BAD_REQUEST),
    FAIL_TO_UPDATE_USER_FIREBASE_TOKEN("US01","Fail to update user`s firebase token", HttpStatus.SC_BAD_REQUEST),
    UNKNOWN_ERROR("9999", "UNKNOWN_ERROR", HttpStatus.SC_BAD_REQUEST),
    UNAUTHORIZED_ACCESS_ERROR("BC01", "UNAUTHORIZED ACCESS", HttpStatus.SC_UNAUTHORIZED),
    NOT_FOUND_ERROR("BC02", "NOT FOUND", HttpStatus.SC_NOT_FOUND),
    FORBIDDEN_ACCESS_ERROR("BC03", "FORBIDDEN ACCESS", HttpStatus.SC_FORBIDDEN),
    JWT_INVALID_SIGNATURE("JW01", "Invalid JWT signature", HttpStatus.SC_UNAUTHORIZED),
    JWT_INVALID("JW99", "Invalid JWT token", HttpStatus.SC_UNAUTHORIZED),
    JWT_EXPIRED_TOKEN("JW02", "Expired JWT token", HttpStatus.SC_UNAUTHORIZED),
    JWT_UNSUPPORTED_TOKEN("JW03","Unsupported JWT token", HttpStatus.SC_UNAUTHORIZED),
    JWT_ILLEGALARGUMENT("JW04","JWT claims string is empty", HttpStatus.SC_UNAUTHORIZED),
    JWT_CAN_NOT_FIND_TOKEN("JW05", "Can not find the jwt Token", HttpStatus.SC_BAD_REQUEST),
    TOKEN_ERROR_INVALID_CLIENT("TK01", "INVALID_CLIENT", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_UNAUTHORIZED_CLIENT("TK02", "UNAUTHORIZED_CLIENT", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_INVALID_GRANT("TK03", "INVALID_GRANT", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_INVALID_SCOPE("TK04", "INVALID_SCOPE", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_INVALID_TOKEN("TK05", "INVALID_TOKEN", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_REDIRECT_URI_MISMATCH("TK06", "REDIRECT_URI_MISMATCH", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_UNSUPPORTED_GRANT_TYPE("TK07", "UNSUPPORTED_GRANT_TYPE", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_UNSUPPORTED_RESPONSE_TYPE("TK08", "UNSUPPORTED_RESPONSE_TYPE", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_ACCESS_DENIED("TK09", "ACCESS_DENIED", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_INVALID_REQUEST("TK10", "INVALID_REQUEST", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_ALREADY_LOGGED_IN("TK11","ALREADY_LOGGED_IN" , HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_DEVICE_INFO_IS_EMPTY("TK12", "DEVICE_INFO_IS_EMPTY", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_FAIL_TO_REVOKE_ACCESS_TOKEN("TK13", "AccessToken을 파기하는데 실패하였습니다. 나중에 다시 시도해주세요.", HttpServletResponse.SC_BAD_REQUEST),
    TOKEN_ERROR_UNKNOWN("TK99", "UNKNOWN_TOKEN_ERROR", HttpServletResponse.SC_BAD_REQUEST)
}