version: "3.7"
services:
  parcel-db:
    image: mariadb:10.6
    command: --lower_case_table_names=1
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=parcel
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=parcel-svc
      - MYSQL_PASSWORD=parcel-pass
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
